# Generated by Django 6.1.1 on 2026-09-20 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(help_text='Clinic registration number, e.g. PT-00142', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9\\-]+$', 'Use letters, digits and hyphens only.')])),
                ('full_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a 10-digit mobile number.')])),
                ('diagnosis', models.CharField(max_length=200)),
                ('consulting_doctor', models.CharField(max_length=120)),
                ('admitted_on', models.DateField()),
                ('status', models.CharField(choices=[('AD', 'Admitted'), ('OP', 'Outpatient'), ('DC', 'Discharged')], default='OP', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-admitted_on', 'full_name'],
            },
        ),
    ]
